[[block]]
block = "pacman"
interval = 10
format= "{both} updates available"
format_singular = "{both} update available"
format_up_to_date = "up to date"
critical_updates_regex = "(linux)"
aur_command = "yay -Qu"
