[theme]
name = "bad-wolf"
[theme.overrides]
separator = ""

[icons]
name = "awesome5"

[[block]]
block = "pacman"
interval = 10
format= "{aur} updates available"
format_singular = "{aur} update available"
format_up_to_date = "up to date"
critical_updates_regex = "(linux)"
aur_command = "yay -Qu"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
on_collapsed_click = "spotify"
marquee = true
marquee_interval = 2
marquee_speed = 0.6
dynamic_width = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mum}MB/{MTm}MB"
#format_swap = "{SFm}%"
icons = true
clickable = false
interval = 5

[[block]]
block = "cpu"
format = "{utilization} {frequency}"
interval = 1

[[block]]
block = "sound"
format = "{volume}%"
on_click = "i3-sensible-terminal -e pulsemixer"

[[block]]
block = "backlight"
device = "intel_backlight"
step_width = 5

[[block]]
block = "bluetooth"
mac = "DC:2C:26:FA:A5:D9"
label = "k8"

[[block]]
block = "battery"
device = "BAT1"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "net"
device = "eth0"
format = "{ip} {speed_down}"
interval = 5
use_bits = false

[[block]]
block = "net"
device = "wlp2s0"
format = "{signal_strength} {ip}"
#format_alt = "{ssid} {signal_strength} {ip} {speed_down}"
interval = 5
use_bits = false

[[block]]
block = "time"
interval = 60
format = "%a %d.%m %R"
